// AmplifX Primer list created with AmplifX <version> 1.7.0</version><parameters>40/60/50/68/4</parameters>
<OwnerIndex></OwnerIndex>
<Familly></Familly>
<primer><UID>0000001</UID><Cat></Cat><ID>Pr0001</ID><SEQ>AGAGTGAAGCGACCCATGAA</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>95</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>2</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>12</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>95</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000002</UID><Cat></Cat><ID>Pr0002</ID><SEQ>TCTCTGTGCATGGCCTGTAA</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>95</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>2</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>16</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>95</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000003</UID><Cat></Cat><ID>Pr0003</ID><SEQ>TTACAGGCCATGCACAGAGA</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>90</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>3</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>16</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>90</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000004</UID><Cat></Cat><ID>Pr0004</ID><SEQ>CTTGAGTGTGTGGCTTTCGT</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>2</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>10</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000005</UID><Cat></Cat><ID>Pr0005</ID><SEQ>GGATAGAGTGAAGCGACCCA</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>55</Value><Class>Good</Class></GC><EndStability><Value>4</Value><Class>Bad</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>16</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000006</UID><Cat></Cat><ID>Pr0006</ID><SEQ>TTTCTCTCTGTGCATGGCCT</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>80</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>4</Value><Class>Bad</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>10</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>80</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000007</UID><Cat></Cat><ID>Pr0007</ID><SEQ>AGATGCTGCCGAAGAATTGC</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>2</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>14</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000008</UID><Cat></Cat><ID>Pr0008</ID><SEQ>GCTTTGTCCAGTGGCTGTAG</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>90</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>55</Value><Class>Good</Class></GC><EndStability><Value>3</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>16</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>90</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000009</UID><Cat></Cat><ID>Pr0009</ID><SEQ>CGAAGATGCTGCCGAAGAAT</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>50</Value><Class>Good</Class></GC><EndStability><Value>1</Value><Class>Good</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>14</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000010</UID><Cat></Cat><ID>Pr0010</ID><SEQ>CTACAGCTTTGTCCAGTGGC</SEQ><NAME></NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>55</Value><Class>Good</Class></GC><EndStability><Value>4</Value><Class>Bad</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>14</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
<primer><UID>0000011</UID><Cat></Cat><ID>Pr0011</ID><SEQ>CTACAGCTTTGTCCAGTGGC</SEQ><NAME>copia </NAME><OWNER></OWNER><L>20</L><Q>85</Q><TM>55</TM><details><polyX><Value>0</Value><Class>Good</Class></polyX><GC><Value>55</Value><Class>Good</Class></GC><EndStability><Value>4</Value><Class>Bad</Class></EndStability><TM><Value>55</Value><Class>Good</Class></TM><Triplet><Value></Value><Class>Good</Class></Triplet><Doublet><Value></Value><Class>Good</Class></Doublet><SelfDimer><Value>14</Value><Class>Good</Class></SelfDimer><SelfEndDimer><Value>0</Value><Class>Good</Class></SelfEndDimer><GlobalNote>85</GlobalNote><COMMENT></COMMENT></details></primer>
